FROM python:3

WORKDIR /usr/src/app

RUN pip install Flask
RUN pip install pytest
RUN pip install pytest-xdist
RUN pip install future
RUN pip install -U pylint
RUN pip install autopep8

COPY . .

EXPOSE 5000