FROM python:3

WORKDIR /usr/src/app

RUN pip install Flask
RUN pip install pytest
RUN pip install pytest-xdist
RUN pip install pylint
RUN pip install autopep8
RUN pip install snakeviz
RUN pip install pytest-profiling
RUN pip install colorama

COPY . .

EXPOSE 5000